website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = db.get_seller_by_email(email)  
        user2 = db.get_buyer_by_email(email)  

        if user:
            if user.password == password:
                flash('Logged in successfully as seller!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.profile'))
            else:
                flash('Incorrect password for seller, try again.', category='error')

        elif user2:
            if user2.password == password:

                flash('Logged in successfully as buyer!', category='success')
                login_user(user2, remember=True)
                return redirect(url_for('views.profile'))
            else:
                flash('Incorrect password for buyer, try again.', category='error')
        else:    
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        last_name =  request.form.get('lastName')
        phone = request.form.get('phone')
        username = request.form.get('username')
        user_type = int(request.form.get('userType'))

        #CHECK IF USERNAME AND EMAIL ARE UNIQUE
        
        seller_mail = db.get_seller_by_email(email)  
        seller_username = db.get_seller_by_username(username)  
        buyer_mail = db.get_seller_by_email(email)  
        buyer_username = db.get_seller_by_username(username)  


        if seller_mail or buyer_mail:
            flash('E-mail already registered.', category='error')
        elif seller_username or buyer_username:
            flash("Username already exists", category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 4:
            flash('Username must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(last_name) < 2:
            flash('Last name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        elif len(phone) < 10:
            flash('Phone number not valid.', category='error')
        elif user_type == 0:
            flash('Select a user type', category='error')

       #ADD TO DATABASE     
        else:
            if user_type == 2:
                db.add_seller(username, password1, first_name, last_name, phone, email, 1)
                flash('Seller account created!', category='success')

            elif user_type == 1:
                print(password1)
                db.add_buyer(username, password1, first_name, last_name, phone, email)
                flash('Buyer account created!', category='success')

            return redirect(url_for('auth.home'), user=current_user)

    return render_template("sign-up.html", user=current_user)

website/templates/add-class.html
{% extends "base.html" %} 

{% block title %}Sign Up{% endblock %} 

{% block content %}
    
    <form method="POST">
    <br />
      <h3 align="center">Add a Seller Class</h3>

      <div class="form-group">
        <label for="id">Class ID</label>
        <input
          type="id"
          class="form-control"
          id="id"
          name="id"
          placeholder="Enter an integer ID"
        />
      </div>

      <div class="form-group">
        <label for="title">Class Title</label>
        <input
          type="title"
          class="form-control"
          id="title"
          name="title"
          placeholder="Enter Title"
        />
      </div>
      
      <div class="form-group">
        <label for="minsell">Minimum amount of sells</label>
        <input
          type="minsell"
          class="form-control"
          id="minsell"
          name="minsell"
          placeholder="Give a number"
        />
      </div>
      <div class="form-group">
        <label for="minrate">Minimum rating</label>
        <input
          type="minrate"
          class="form-control"
          id="minrate"
          name="minrate"
          placeholder="Enter a value between 0 and 5"
        />
      </div>
      <div class="form-group">
        <label for="cargo">Cargo price</label>
        <input
          type="text"
          class="form-control"
          id="cargo"
          name="cargo"
          placeholder="Enter a number in TL"
        />
      </div>
      <div class="form-group">
        <label for="percent">Percent</label>
        <input
          type="text"
          class="form-control"
          id="percent"
          name="percent"
          placeholder="Enter a value between 0 and 100"
        />
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <br />

    </form>


{% endblock %}
    

website/templates/admin.html
{% extends "base.html" %} 
{% block title %}Class types{% endblock %} 

{% block content %}
<br />
<h1> Class Types</h1>
<br />
<ul>
    {% for thing in classes %}
      <li> Title: {{ thing[1] }} Minimum sold products: {{ thing[2] }}, Minimum rating: {{ thing[2] }}, Cargo price: {{ thing[3] }}, Percentage: {{ thing[4] }} </li>
    {% endfor %}  
</ul>

<div class="container">
    <button type="submit"><a href="{{ url_for('admin.add_class') }}">Add a class</a></button>
    <button type="submit"><a href="{{ url_for('admin.change_class') }}">Alter a class</a></button>
    <button type="submit"><a href="{{ url_for('admin.delete_class') }}">Delete a class</a></button>
    <button type="submit"><a href="{{ url_for('admin.delete_user') }}">Delete user</a></button>
    <button type="submit"><a href="{{ url_for('admin.change_sellerinfo') }}">Change Seller Statistics</a></button>

</div>
<br />
<br />
<br />
<br />

{% endblock %}

{% block change_title %}{% endblock %} 

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <style>
      /* Modify the background color */
       
      .navbar-custom {
          background-color: rgb(245, 221, 194);
      }
      /* Modify brand and text color */
       
      .navbar-custom .navbar-brand,
      .navbar-custom .navbar-text {
          color: rgb(235, 176, 205);
      }
      .nav-link {
        color: rgb(21, 21, 26) !important;
      } 
      body { background: rgb(226, 214, 185) !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */

      .rating {
      unicode-bidi: bidi-override;
      direction: rtl;
      }
      .rating > span {
     display: inline-block;
     position: relative;
      width: 1.1em;
    }
    .rating > span:hover:before,
    .rating > span:hover ~ span:before {
       content: "\2605";
       position: absolute;
    }
    /* The switch - the box around the slider */
.switch {
  position: relative;
  display: inline-block;
  width: 60px;
  height: 34px;
}

/* Hide default HTML checkbox */
.switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

/* The slider */
.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 26px;
  width: 26px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
/* Style the tab */
.tab {
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}

/* Style the buttons that are used to open the tab content */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
}

  </style>

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-custom bg-light">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <img src="\static\logo.png"> 
          <a class="nav-item nav-link" id="home" href="/">Home</a>

          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="profile" href="/profile">Profile</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign up</a>
          {% endif %}

          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Check Out
            </a>
          
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="nav-item nav-link" id="sellers" href="/sellers">Sellers</a>
              <a class="nav-item nav-link" id="buyers" href="/buyers">Buyers</a>
              <a class="nav-item nav-link" id="product" href="/product">Products</a>
            </div>
          </div>
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/buyers.html
{% extends "base.html" %} 
{% block title %}Buyers ordered by username{% endblock %} 

{% block content %}
<br />
<h1> All buyers</h1>
<br />
<ul>
    {% for thing in buyers %}
      <li>{{ thing[0] }} registered at {{ thing[1] }}</li>
    {% endfor %}  
</ul>



{% endblock %}

website/templates/change-class.html
{% extends "base.html" %} 

{% block title %}Sign Up{% endblock %} 

{% block content %}
    
    <form method="POST">
    <br />
      <h3 align="center">Change a Seller Class</h3>

      <div class="form-group">
        <label for="titleold">Old class title</label>
        <input
          type="titleold"
          class="form-control"
          id="titleold"
          name="titleold"
          placeholder="Enter Old Title"
        />
      </div>

      <div class="form-group">
        <label for="title">New class title</label>
        <input
          type="title"
          class="form-control"
          id="title"
          name="title"
          placeholder="Enter New Title"
        />
      </div>

      <div class="form-group">
        <label for="title">Class ID</label>
        <input
          type="id"
          class="form-control"
          id="id"
          name="id"
          placeholder="Enter an integer ID"
        />
      </div>

      
      
      <div class="form-group">
        <label for="minsell">Minimum amount of sells</label>
        <input
          type="minsell"
          class="form-control"
          id="minsell"
          name="minsell"
          placeholder="Give a number"
        />
      </div>
      <div class="form-group">
        <label for="minrate">Minimum rating</label>
        <input
          type="minrate"
          class="form-control"
          id="minrate"
          name="minrate"
          placeholder="Enter a value between 0 and 5"
        />
      </div>
      <div class="form-group">
        <label for="cargo">Cargo price</label>
        <input
          type="text"
          class="form-control"
          id="cargo"
          name="cargo"
          placeholder="Enter a number in TL"
        />
      </div>
      <div class="form-group">
        <label for="percent">Percent</label>
        <input
          type="text"
          class="form-control"
          id="percent"
          name="percent"
          placeholder="Enter a value between 0 and 100"
        />
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <br />

    </form>


{% endblock %}
    

website/templates/delete-class.html
{% extends "base.html" %} 

{% block title %}Delete{% endblock %} 

{% block content %}
    
    <form method="POST">
    <br />
      <h3 align="center">Delete Seller Class</h3>

      <div class="form-group">
        <label for="title">Title of class to delete</label>
        <input
          type="title"
          class="form-control"
          id="title"
          name="title"
          placeholder="Enter a Title"
        />
        <br />

        <button type="submit" class="btn btn-primary">Submit</button>

      </div>


{% endblock %}
    

website/templates/delete-user.html
{% extends "base.html" %} 

{% block title %}Delete{% endblock %} 

{% block content %}
    
    <form method="POST">
    <br />
      <h3 align="center">Delete Seller or a Buyer</h3>

      <div class="form-group">
        <label for="username">Username to be deleted</label>
        <input
          type="username"
          class="form-control"
          id="username"
          name="username"
          placeholder="Enter a username"
        />
        <br />

        <button type="submit" class="btn btn-primary">Submit</button>

      </div>


{% endblock %}
    

website/templates/home.html
{% extends "base.html" %}

{% block title %}
Home Page
{% endblock %}

<link rel="stylesheet" href="templates/css/home.css">

{% block content %}
<br />
<h1 align="center"> WELCOME </h1>
<table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr><td align="center">
    <img src="/static/logoBig.png">
    </td></tr>
    </table>

<br />
<h2 align="center"> SELL AND BUY SECOND HAND ITEMS IN AUCTIONS</h2>
<br />

<h2 align="center"> Currently </h2>
<div align="center">
         <li >Sellers:  {{ seller }}</li>
         <li >Buyers:  {{ buyer }}</li>
         <li >Products:  {{ product }}</li>
    </ul>
</div>
<br />

{% if user.is_authenticated %}
{% else %}
<p align="center"><a href="{{ url_for('auth.login') }}">Login</a> or  <a href="{{ url_for('auth.sign_up') }}">Sign Up</a></p> 
{% endif %}
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %} 
{% block title %}Profile{% endblock %} 

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='starter-template.css')}}">
{% endblock %}

{% block content %}
<br />
<br />
<h1> Welcome to your profile,  {{ current_user.username }}</h1>
<br />

{% if seller_class %}
<div>
    <h2> You are a {{ seller_class.title }} class seller.</h2>
</div>
<br />
{% endif %}


<h2> Account Info </h2>
{% if current_user %}
<div>
    <ul>
        <li>Name : {% if current_user.name %}{{ current_user.name }}{% endif %}</li>
        <li>Surname : {% if current_user.surname%}{{ current_user.surname }}{% endif %}</li>
        <li>User Type : {% if current_user.payment %} Seller 
            {% else %} Buyer
            {% endif %}</li>

    </ul>
</div>
<br />
{% endif %}

{% if seller_info %}
<h2> Your stats </h2>
<div>
    <ul>
        <li>Number of sells : {{ seller_info.numofsells }}</li>
        <li>Number of products listed : {{ seller_info.numofproducts }}</li>
        <li>Total bids : {{ seller_info.totalbids }}</li>
        <li>Rating : {{ seller_info.rating }} / 5
             <span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span></li>
            
    </ul>
</div>
<br />
{% endif %}

<div class="container">
    <button type="submit"><a href="{{ url_for('update_profile') }}">Change Password</a></button>
    <button type="submit"><a href="{{ url_for('update_info') }}">Update Profile</a></button>
    {% if user.is_admin %}
    <button type="submit"><a href="{{ url_for('admin.admin_page') }}">Admin</a></button>
    {% endif %}
</div>

{% endblock %}

website/templates/sellers.html
{% extends "base.html" %} 
{% block title %}Sellers ordered by number of sells{% endblock %} 

{% block content %}
<br />
<h1> Sellers</h1>
<p>Click on the buttons to display sellers in different orderings:</p>

<div class="tab">
  <button class="tablinks" onclick="openCity(event, 'Rating')">Rating</button>
  <button class="tablinks" onclick="openCity(event, 'Sells')">Sells</button>
</div>


<div id="Rating" class="tabcontent">
  <ul>
    <table>
      <tr>
        <th>Seller</th>
        <th>Listed Items</th>
        <th>Sold Items</th>
        <th>Total Bids</th>
        <th>Rating</th>
      </tr>
      <tr>
        {% for thing in rating %}
        <tr>
        <td>{{ thing[0] }}  </td>
        <td>{{ thing[1] }}  </td>
        <td>{{ thing[2] }}  </td>
        <td>{{ thing[3] }}  </td>
        <td>{{ thing[4] }}  </td>
      </tr>
        {% endfor %} 
      </tr>
    </table>
  
    
  </ul>
</div>

<div id="Sells" class="tabcontent">
  <ul>
    <table>
      <tr>
        <th>Seller</th>
        <th>Listed Items</th>
        <th>Sold Items</th>
        <th>Total Bids</th>
        <th>Rating</th>
      </tr>
      <tr>
        {% for thing in sells %}
        <tr>
        <td>{{ thing[0] }}  </td>
        <td>{{ thing[1] }}  </td>
        <td>{{ thing[2] }}  </td>
        <td>{{ thing[3] }}  </td>
        <td>{{ thing[4] }}  </td>
      </tr>
        {% endfor %} 
      </tr>
    </table>
  
    
  </ul>
</div>

<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>


{% endblock %}

website/templates/sign-up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}

<form method="POST">
  <h3 align="center">Become a seller or a buyer!</h3>

  <div class="form-group" style="width:200px;">
      <select name="userType" id="type">
      <option value="0">Select user type:</option>
      <option value="1">Buyer</option>
      <option value="2">Seller</option>
    </select>
  </div>

  <div class="form-group">
    <label for="username">Username</label>
    <input
      type="username"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter username"
    />
  </div>
  <div class="form-group">
    <label for="phone">Phone number</label>
    <input
      type="phone"
      class="form-control"
      id="phone"
      name="phone"
      placeholder="(0___) ___ - __ - __"
    />
  </div>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="lastName">Last Name</label>
    <input
      type="text"
      class="form-control"
      id="lastName"
      name="lastName"
      placeholder="Enter last name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/update-info.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Change Info
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='signin.css')}}">
{% endblock %}

{% block content %}

<div class="container">

    <form class="form-signin" method="POST" action="/update-info">
        <h2 class="form-signin-heading">Change your Info</h2>
        {{ update.hidden_tag() }}
        {{ wtf.form_field(update.name) }}
        {{ wtf.form_field(update.surname) }}
        {{ wtf.form_field(update.phone) }}
        <button class="btn btn-lg btn-primary" type="submit">Attempt to change</button>
    </form>

</div> <!-- /container -->
{% endblock %}

website/templates/update-password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Change Password
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='signin.css')}}">
{% endblock %}

{% block content %}

<div class="container">

    <form class="form-signin" method="POST" action="/update-password">
        <h2 class="form-signin-heading">Change your password, {{ current_user.username }}</h2>
        {{ update.hidden_tag() }}
        {{ wtf.form_field.csrf_token }}
        {{ wtf.form_field(update.oldpassword) }}
        {{ wtf.form_field(update.newpassword) }}
        {{ wtf.form_field(update.confirm) }}
        <button class="btn btn-lg btn-primary" type="submit">Attempt to change</button>
    </form>

</div> <!-- /container -->
{% endblock %}